- .gitignore
- .hound.yml
- .jscsrc
- .jshintignore
- .jshintrc
- .prospector.yaml
- .travis.yml
- CHANGES.rst
- CONTRIBUTING.rst
- Dockerfile
- LICENSE
- Makefile
- README.rst
- bouncer/__init__.py
- bouncer/scripts/redirect.js
- bouncer/scripts/test/redirect-test.js
- bouncer/static/images/hypothesis-icon.svg
- bouncer/static/images/sad-annotation.svg
- bouncer/static/styles/bouncer.css
- bouncer/templates/annotation.html.jinja2
- bouncer/templates/base.html.jinja2
- bouncer/templates/notfound.html.jinja2
- bouncer/test/views_test.py
- bouncer/views.py
- karma.config.js
- package.json
- setup.py
Working proof of concept, given suitable changes to your local Chrome extension (and hacking this repo's code to include your extension's ID instead of mine), this will redirect you to the extension or (if you disable the extension) to Via.
> First pull request

- Dockerfile
- Makefile
- README.rst
- bouncer/views.py
- gunicorn.conf.py
- setup.py
Statsd is configured using environment variables documented in the README.
Each view callable reports its result to statsd using a naming convention based on [this advice](https://matt.aimonetti.net/posts/2013/06/26/practical-guide-to-graphite-monitoring/), e.g. "views.annotation.404.annotation_not_found", "views.annotation.200".
Separately a `NewRequest` subscriber increments a "requests" counter that simply counts the number of incoming requests regardless of which view (if any) gets called and what its outcome is.
> Report some initial stats to statsd

- README.rst
- bouncer/__about__.py
- bouncer/__init__.py
- bouncer/sentry.py
- bouncer/views.py
- setup.py
Report Python exceptions to a Sentry project.
- Raven (the official Python client for Sentry) is added to the
requirements in setup.py.
- The Sentry DSN (the URI that's needed to authenticate to Sentry) is
read from the SENTRY_DSN environment variable like all other config
settings in bouncer.
- bouncer/sentry.py is a new module that contains all the new
Sentry/raven stuff.
We add a raven client object configured with the SENTRY_DSN from the
environment as request.raven, so that it can be accessed by our raven
tween.
Then we wrap the existing bouncer Pyramid app in a Pyramid tween that
catches any exceptions, reports them to Sentry, then re-raises the
exception.
Any uncaught exceptions raised anywhere in the code, e.g. in a view
callable, will be caught and reported to Sentry by this …
> Report Python exceptions to Sentry

- setup.py
Just something I noticed while going through the code.
> Fix Python version in setup.py classifiers

- Dockerfile
And install pip via the official script, instead of getting the
python-pip package which installs Python 2.
Fixes #14
> Use gliderlabs/alpine as base Docker image

- bouncer/scripts/redirect.js
- bouncer/scripts/test/redirect-test.js
If chrome.runtime.lastError is defined then log it with console.error()
and always redirect to Via instead of Chrome.
Fixes #9
> Check chrome.runtime.lastError

- bouncer/test/util_test.py
- bouncer/test/views_test.py
- bouncer/util.py
- bouncer/views.py
This is branched off of <https://github.com/hypothesis/bouncer/pull/10>. Added some defensive coding against Elasticsearch document variability. I've tested this on ~100,000 annotations from the production hypothes.is API.
> Do not crash on bad annotations

- .gitignore
- MANIFEST.in
- Makefile
- setup.cfg
* Adds make tasks for building standard Python sdist tarballs.
* Adds make clean task.
* Builds docker with the `dev` tag.
* Allows for future production Docker builds through the sdist tarballs.
I've been wondering recently how we actually build the development and production docker images with h. So after looking into it I've decided to implement it for bouncer.
There's probably some things missing or could be done better, please advise!
> Makefile and Docker build improvements

- bouncer/__init__.py
- bouncer/templates/annotation.html.jinja2
- bouncer/templates/base.html.jinja2
- bouncer/templates/error.html.jinja2
The CSS in the bouncer production deployment isn't being loaded because
of a mixed-content warning. Pyramid generates http:// URLs for static
assets, and bouncer is deployed with https://.
To make Pyramid generate static URLs with the same protocol as the
request you need to do:
config.add_static_view(name="//htp.is/static", path="static")
But we can't hardcode "//htp.is/static" (this differs between our stage
and production deployments, for one thing) so make it configurable by a
new environment variable.
> Serve static URLs with same protocol as the site

- README.rst
- bouncer/__init__.py
- bouncer/sentry.py
- bouncer/test/views_test.py
- bouncer/views.py
```
Fix exception handling
1. Fix the front page.
The front page raises an HTTPFound which is supposed to redirect the
browser, but which was being caught by the custom exception view
(which was catching all HTTPExceptions) and turned into an error page.
We no longer have a conteext=httpexceptions.HTTPException view so the
redirect now works as intended.
2. Don't report HTTPRedirection (3xx) and HTTPNotFound (404) to Sentry.
These were being caught by the Raven tween and reported to Sentry.
The Raven tween is now gone, replaced by an exception view (see 3
below) and we have an
@view.view_config(context=httpexceptions.HTTPError)
@view.view_config(context=httpexceptions.HTTPServerError)
view that catches deliberately raised Pyramid exceptions and shows
the user an error page but does not …
```
> Fix the front page

- bouncer/templates/annotation.html.jinja2
- bouncer/test/views_test.py
- bouncer/views.py
Currently the text under the spinner and the page title say
"redirecting." Change that to "Loading annotation for <url/path>"
so that the user has a better idea of what is hapening and what
page he can expect to be redirected to.
> Display document url when redirecting from bouncer.

- bouncer/__init__.py
This should be merged after we're happy with the PostgreSQL migration and want
to switch bouncer to the new index.
> Switch default index to `hypothesis`

- bouncer/test/util_test.py
- bouncer/util.py
Fall back to http document link when PDF annotation
We now store the PDF fingerprint in the target source for annotations
made on PDF files. To be able to still redirect the user to the PDF, we
try and load an http/https URL from the document's links.
> Redirect PDF annotations

- bouncer/scripts/redirect.js
Use window.location.replace(), instead of assigning to window.location,
to redirect the browser from JavaScript.
The difference is that the page that did the window.location.replace()
(the bouncer https://hyp.is/* page) will not be added to the browser's
history.
Previously bouncer was breaking the browser's back button:
1. User is on page A and clicks on a bouncer (hyp.is) link
2. The JavaScript on the bouncer (hyp.is) page redirects them to
example.com
3. On example.com the user clicks the browser's back button and is taken
back to the bouncer (hyp.is) page.
4. The JavaScript on the bouncer (hyp.is) page redirects them to
example.com...
The user cannot get back to page A (except by hitting back twice
quickly, or long-clicking on back and selecting it from the dropdown).
With …
> Don't break the back button

- bouncer/test/util_test.py
- bouncer/util.py
This relies on https://github.com/hypothesis/h/pull/3869 being merged,
deployed to production, and a full reindex being run. This will also fix
the issue that is tracked here: https://github.com/hypothesis/h/issues/3867
> Read web link from new `web_uri` when a URN is found

- bouncer/__init__.py
- bouncer/search.py
- bouncer/test/search_test.py
- bouncer/test/views_test.py
- bouncer/util.py
- bouncer/views.py
This commit extracts the Elasticsearch client (and its provision on the request object) into its own module in preparation for additional changes to the client to include: TLS support, and possibly AWS Auth (signed requests) so that we don't need to whitelist IPs on our Elasticsearch cluster.
> Extract Elasticsearch client into own module

- README.rst
- bouncer/__init__.py
- bouncer/search.py
- bouncer/test/search_test.py
- setup.py
This commit enables AWS Auth v4 request signing if all three of the following environment variables are set:
- ELASTICSEARCH_AWS_ACCESS_KEY_ID
- ELASTICSEARCH_AWS_SECRET_ACCESS_KEY
- ELASTICSEARCH_AWS_REGION
This allows us to make requests to an AWS Elasticsearch cluster without knowing in advance the public IP from which those requests will be made.
When these environment variables are not set, the configuration is exactly as before.
~_**N.B.** This PR depends on #33 and will need rebasing after that merges._~
> Optional AWS Auth v4 request signing

- Dockerfile
~~This depends on #36 and needs to be rebased after #36 has been merged.~~
---
This updates the Docker base image to alpine 3.4, bringing it to the same version as we use with h.
> Docker updates

- Dockerfile
- bin/start-collectd
- conf/collectd.conf
- conf/supervisord.conf
~~This depends on #38 and needs to be rebased after #38 has been merged.~~
---
In order to get system metrics from bouncer running on Skyliner, we need to
run collectd inside the container.
This adds the exact same collectd configuration as we currently use on
the old infrastructure instances, except for the removal of the nptd
plugin which doesn't work due to [a
bug](collectd/collectd#932).
The `start-collectd` script will configure collectd to send the metrics
to graphite if the `GRAPHITE_HOST` environment variable is set,
otherwise it will configure the basic `write_log` plugin.
Similar to that it tries to get the EC2 instance id through the metadata
API, if it isn't available it will fallback to the local hostname
(calling `hostname`).
> Run collectd inside docker container for system metrics

- Dockerfile
- bin/init-env
Which sets up some environment variables, most importantly it adds the
EC2 instance id (or default to `hostname`) at the end of
`STATSD_PREFIX`.
> Wrap supervisor into an `init-env` script

- bouncer/views.py
- tests/bouncer/views_test.py
This can aid in debugging to easily know which version we're currently
running.
> Expose bouncer version in /_status endpoint

- bouncer/views.py
- tests/bouncer/views_test.py
Add a `/go?url={url}` endpoint which takes the user to a given URL with
the annotation layer enabled, optionally with the client configured to
initially show only annotations matching a given filter by specifying a
"q={query}" parameter.
The {query} is passed directly to the search input in the client.
For the API design rationale and discussion, see [1] and [2].
[1] https://gist.github.com/robertknight/85c9dfc89910288e84588903ab1010a3
[2] https://groups.google.com/a/list.hypothes.is/forum/#!topic/dev/sFH-3xmeK8Y
----
**Testing**
1. Visit https://BOUNCER.URL/go?url=https://example.com
2. This should open "example.com" in Via with the annotation layer enabled. Note that the sidebar does not automatically open if no query is supplied.
3. Visit …
> Add `/go` endpoint for visiting a URL with annotations.

- karma.config.js
- package.json
Update JS dev dependencies to latest versions to fix the many
deprecation warnings during package installation.
"watchify" was added because karma-browserify now requires it as a peer
dependency.
"karma-phantomjs2-launcher" was replaced with "karma-phantomjs-launcher" because the latter now does use PhantomJS v2 and the former recommends this change during package installation.
> Update JS dev dependencies

- tox.ini
This should fix coverage reporting on codecov, which hasn't been working
for 7 months.
--parallel causes coverage to generate output files named like
.coverage.$HOSTNAME.8089.232834 which codecov is unable to find. You
need to combine those into a single .coverage file by running coverage
combine.
Since we're not actually running more than one coverage task at once
--parallel is pointless, and if you remove it then coverage just
generates the one .coverage file that codecov should be able to find in
the first place.
> Don't pass --parallel to coverage run

- bouncer/__init__.py
- bouncer/templates/annotation.html.jinja2
- bouncer/templates/base.html.jinja2
- bouncer/util.py
- bouncer/views.py
- tests/bouncer/search_test.py
- tests/bouncer/util_test.py
- tests/bouncer/views_test.py
https://docs.google.com/document/d/1UPPPgLLPMTwxh83BITCiSK7QxfwpORONiZF9vFL4doA
these flake8 complaints were for the pre-existing HEAD (ce16736e40222dc0caab041f07ac2c6a53e4ed35)
```
./views.py:75:11: E111 indentation is not a multiple of four
./views.py:140:64: E999 SyntaxError: invalid syntax
./__init__.py:45:80: E501 line too long (97 > 79 characters)
./__init__.py:47:80: E501 line too long (105 > 79 characters)
./__init__.py:49:80: E501 line too long (83 > 79 characters)
./_version.py:62:44: F821 undefined name 'FileNotFoundError'
```
> use quote and text (if available) to enhance share card

- tox.ini
On for example Ubuntu 17.10 Python 3.6 is installed but Python 3.5
isn't, but the tests were configured to run on 3.5 only. This changes
them to run on any Python 3.x.
> Allow the tests to run on Python 3.6

- setup.cfg
This matches the config we have in the h repo.
This removes line-length related errors for those of us who have flake8 integrated with our editor ([ALE](https://github.com/w0rp/ale) FTW!)
> Add a minimal flake8 config

- tests/bouncer/util_test.py
Many tests in `util_test.py` duplicated the same fixture data for fields
that are expected to be present in every ES annotation JSON document.
Extracting the fixture will make it easier to add new fields to it.
> Extract shared fixture from test cases

- README.rst
- bouncer/app.py
- bouncer/scripts/redirect.js
- bouncer/scripts/test/redirect-test.js
- bouncer/util.py
- bouncer/views.py
- tests/bouncer/util_test.py
- tests/bouncer/views_test.py
**Depends on https://github.com/hypothesis/bouncer/pull/60, will need rebasing.**
If a direct-linked annotation was made on a page that embeds Hypothesis and uses third party accounts then the page is highly likely to be broken if delivered through the Via proxy service since Via does not allow cookies to be read/written amongst other issues. Since we know the page already embeds Hypothesis we can just redirect the user to the original URL in this case.
Whether or not an annotation is "third party" is determined by comparing the "authority" field of the Elasticsearch document with a `HYPOTHESIS_AUTHORITY` setting configured in Bouncer's environment.
**Testing steps**
1. Run the client, h and publisher-account-test-site services with the following env vars configured:
``` …
```
> Redirect user to original URL instead of proxy if annotation was created by a third-party user

- Makefile
As noted at https://pip.pypa.io/en/stable/user_guide/, pip automatically
installs wheels when they are available, so `--use-wheel` is a no-op
which existed because of the counterpart `--no-use-wheel`. That was in
turn removed in favor of `--no-binary` in pip 10.0.
> Remove deprecated and redundant pip `--use-wheel` argument

- README.rst
- bouncer/app.py
- bouncer/search.py
- requirements.txt
- tests/bouncer/search_test.py
- tests/bouncer/views_test.py
Upgrading elasticsearch from 1.5.0 to 6.2.0.
> Connect to elasticsearch 6.2.0 cluster

- README.rst
- bouncer/search.py
- tests/bouncer/views_test.py
Update the default ES port following the merge of https://github.com/hypothesis/h/pull/5215
CC @hmstepanek
> Update the default Elasticsearch port

- .travis.yml
Copy over the Travis caching configuration from the h repo to speed up
future Travis CI builds.
> Add npm and pip caching to speed up Travis builds

- bouncer/views.py
This has been replaced by `bouncer.util.get_pretty_url`.
I noticed this because of the reference to the non-existent (in that file) `NETLOC_MAX_LENGTH` var.
> Remove unused _pretty_url function

- bouncer/embed_detector.py
- bouncer/views.py
- tests/bouncer/embed_detector_test.py
- tests/bouncer/views_test.py
If the target URL is known to embed the client, sending the user
directly to that URL will be a better experience than sending the user
through a proxy service.
There are various ways that we could detect whether a target URL embeds
the client. This commit implements the dumbest possible approach of a
hardcoded list of URL patterns.
The initial list includes a couple of Hypothesis-related URLs. Our first use for this will be in solving https://github.com/hypothesis/product-backlog/issues/814. We'll add the URL pattern(s) for that once they have been confirmed.
> Avoid redirecting user to Via if target URL is known to embed client

- bouncer/embed_detector.py
**Depends on https://github.com/hypothesis/bouncer/pull/155**
Add the URL prefixes supplied by APA to the list of URL patterns assumed to embed the Hypothesis client and therefore not require Via.
Fixes https://github.com/hypothesis/product-backlog/issues/814
> Add APA URL prefixes to embed list

- .coveragerc
- .travis.yml
- Jenkinsfile
- Makefile
- bouncer/util.py
- requirements-dev.txt
- tox.ini
Refactor `Makefile` and `tox.ini` to be the same as the ones used in h and soon to be used in all our apps.
Also add a `.coveragerc` file, the same as h has, instead of passing args to it on the command line.
`requirements-dev.txt` is removed as its no longer needed. There weren't actually any "dev" (as in running the dev server) requirements in here, they were all requirements for running the tests and linter, and those requirements are listed in `tox.ini` instead now.
```shellsession
$ make help
make help              Show this help message
make dev               Run the app in the development server
make lint              Run the code linter(s) and print any warnings
make test              Run the unit tests
make coverage          Print the unit test coverage report
make codecov …
```
> Refactor tox.ini and Makefile

- .travis.yml
- Dockerfile
- Jenkinsfile
- Makefile
- tox.ini
The Alpine upgrade is needed for Python 3.6, which was added in Alpine
3.6: https://alpinelinux.org/posts/Alpine-3.6.0-released.html
> Upgrade to Python 3.6 and Alpine Linux 3.8

- Dockerfile
This works around a build failure with the gliderlabs/alpine image [1]
and matches the Docker image source we use for h. This change is also
recommended by Glider Labs [2] who maintain both images.
The resulting image is slightly larger (167MB vs 160MB for latest
released image) but there is plenty of room to reduce the image size in other
ways.
[1] https://github.com/gliderlabs/docker-alpine/issues/464
[2] https://github.com/gliderlabs/docker-alpine/blob/71099f56701722443807578f1771b07670399c46/docs/build.md#differences
> Use the official Alpine Linux base image

- Dockerfile
collectd was failing to start in an endless loop because the collectd disk
plugin was missing.
> Add missing collectd-disk plugin

- Dockerfile
To the latest version. This is to allow Dependabot's Docker support to
work.
> Pin Docker base image version

- bouncer/views.py
- tests/bouncer/views_test.py
Part of https://github.com/hypothesis/product-backlog/issues/864
For the Community Groups project, we need to be able to
generate bouncer links for a URL that automatically
focus a specific group (by group pubid) in the client
layer.
The client has been updated to understand an
extended fragment syntax (`#annotations:group:{pubid}`).
This adds the logic such that bouncer can accept a
`group` query parameter on the `/go` route and
generate a redirect with the correct fragment
syntax for focusing a group.
I clarified a few comments while in there, but otherwise didn't mess with stuff too much.
> Add the ability to focus a group via querystring parameter

- README.md
- tox.ini
Set default values for environment variables in dev, to get bouncer working with local h and via.
Bouncer doesn't have a DB, and doesn't have any sensitive envvars that need to be set, so there's no need for bouncer to use the devdata repo. It also doesn't have a config file! So use `tox.ini` to set envvars in dev only.
> Set default envvars in dev

- Makefile
- tox.ini
Moving pip-compile command out of Make and the dev requirements to be a separate tox command. This means the dev env is very slightly smaller, the compile env is much smaller and we are following the more layered approach (make on tox, not instead).
> Moving the pip-compile to tox and it's own env

- .coveragerc
- .travis.yml
- Makefile
- README.md
- tox.ini
Much like we did in LMS, removing the optional information of Codecov for a hard limit which must be met to pass the build.
> Remove codecov and add a coverage minimum value

- Jenkinsfile
- Makefile
- tox.ini
1. You can just do `tox -e foo` rather than `tox -e py36-foo`
2. Use `tox -qe` rather than `tox -q -e`
3. Use `@` prefix in Makefile so make doesn't print out each command
before running it
For more explanation see:
hypothesis/h#5866
> Simplify tox commands

- requirements.txt
Re-run `make pip-compile` to recreate the requirements.txt file. This
doesn't change any of the requirements or their versions. It's just that
pip-tools (which `make pip-compile` uses) seems to have changed how it
"annotates" the lines in requirements.txt. So I'm just updating
requirements.txt with the new-style annotations.
> Re-compile requirements.txt

- requirements/dev.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/tests.txt
Usage of requests-aws4auth was removed in 4ef03da532fb255358f1bf1cfd8dc26127a2e612
after we switched over to a new Elasticsearch instance which runs inside
our VPC with access controlled via security groups.
> Remove requests-aws4auth dependency

- bouncer/embed_detector.py
- tests/bouncer/embed_detector_test.py
docdrop.org is a site that hosts various kinds of document (PDFs, video
transcripts and more) with Hypothesis already embedded.
Fixes #389
> Do not embed client on docdrop.org

- .coveragerc
- bouncer/views.py
- tests/functional/views/healthcheck_test.py
- tests/unit/bouncer/views_test.py
Every other app uses "okay" not "ok". This will allow Bouncer's Pingdom alarms to be the same as those for other apps.
It wouldn't do any harm to leave the version number in the status endpoint, but I'm not sure it has much utility and none of our other apps have it.
> Make the status endpoint consistent with other apps

- requirements/dev.txt
- requirements/tests.txt
- tox.ini
For: https://github.com/hypothesis/tox-pip-sync/issues/11
This also recompiles the dependencies afterward using the technique I've been using on the projects done later in case any changes are found. 
This process is to:
* `rm requirements/*.txt`
* `git checkout/requirements.txt` - To preserve the set in live
* `hdev requirements`
> Replace `tox-pip-extensions` with `tox-pip-sync`

- tox.ini
The new "Via 3" version of Via uses 9083 as the development port.
> Update port for local Via service

- .eslintrc
- bouncer/scripts/redirect.js
- bouncer/scripts/test/redirect-test.js
- bouncer/templates/annotation.html.jinja2
- karma.config.js
- package-lock.json
- package.json
Bouncer has only a small amount of JavaScript and used Browserify purely
as a module system provider. With our currently supported browsers and
current version of Karma we can just use native ES modules instead.
Removing Browserify usage will allow us to trim the project's
dependencies.
- Convert `redirect.js` and `redirect-test.js` to ES modules
- Update Karma configuration to load JS files as modules and remove
Browserify usage
- Remove Browserify and associated dependencies
This partially resolves the entry for Bouncer in https://github.com/hypothesis/private-issues/issues/77. Other dependencies (eg. Karma, mocha) also need to be updated to resolve the remaining issues.
----
**Testing:**
Run `make dev`, then check that if you follow an annotation share link from the client or h, the …
> Replace Browserify with ES modules

- requirements/checkformatting.in
- requirements/checkformatting.txt
- requirements/coverage.in
- requirements/coverage.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/format.in
- requirements/format.txt
- requirements/functests.in
- requirements/functests.txt
- requirements/lint.in
- requirements/lint.txt
- requirements/tests.in
- requirements/tests.txt
- tox.ini
**Developers will have to `rm -rf .tox` in their dev envs after merging this** if they see `command not found: pip-sync-faster`.
Simplify our development tooling by removing the `tox-pip-sync` plugin in favour of calling [`pip-sync-faster`](https://github.com/hypothesis/pip-sync-faster) directly from `tox.ini`.
Also add the [`tox-faster`](https://github.com/hypothesis/tox-faster) plugin to `tox.ini`: `tox-faster` is a standalone implementation of a small `tox` speedup that was previously implemented in `tox-pip-sync`.
We did this in LMS a while ago and haven't noticed any problems there:
https://github.com/hypothesis/lms/pull/4191/files
Details
-------
* `pip-sync-faster` is added to all the `requirements/*.in` files (except the production `requirements/requirements.in`). …
> Remove `tox-pip-sync`

- .cookiecutter/includes/.github/workflows/environments.json
- .github/workflows/deploy.yml
- .github/workflows/redeploy.yml
Change the GitHub environment URLs to Bouncer links to a test annotation. These links can actually be clicked on to do a basic test of Bouncer.
> Change to more helpful GitHub environment URLs

- bouncer/embed_detector.py
See https://hypothes-is.slack.com/archives/C04F8GLTT7U/p1674065065018549 for context.
Also split up the list of sites into three groups based on their relation to Hypothesis for ease of scanning.
> Add Semantic Scholar to list of sites that embed the client

- bouncer/embed_detector.py
- tests/unit/bouncer/embed_detector_test.py
I added the exact URL pattern that we were asked to add, but the reader is actually hosted at "www.semanticscholar.org" and Bouncer's matching does not currently ignore "www." as we do in some other places.
> "semanticscholar.org" => "www.semanticscholar.org"

- bouncer/app.py
- bouncer/views.py
- tests/unit/bouncer/app_test.py
- tests/unit/bouncer/views_test.py
Allow the Chrome extension ID to be customized depending on the authority that an annotation is associated with. The extension IDs are specified by setting the `CHROME_EXTENSION_ID` env var to a JSON map of authority to extension ID. The map must contain a "default" field which specifies the extension to use if no other entry matches. The existing syntax of setting `CHROME_EXTENSION_ID` to a single ID string is still supported.
The initial use case for this is to support bouncer links for annotations created using the Hypothesis for Confluence extension. The eventual plan is to fold that integration back into the main extension, so this might be fairly short-lived flexibility.
For example:
```
export CHROME_EXTENSION_ID='{"default":"abc...", "atlassian.hypothes.is": "def..."}'
```
> Support setting a different extension ID per authority

- conf/gunicorn-dev.conf.py
- tox.ini
Use the `WEB_CONCURRENCY` envvar in `tox.ini` instead of the `workers`
setting in `gunicorn-dev.conf.py`. This is how it's already done in the
cookiecutter and is how we do it in prod.
> Use `WEB_CONCURRENCY` instead of `workers` in dev

- Dockerfile
node/npm packages have been renamed
See failure at: https://github.com/hypothesis/bouncer/actions/runs/7569589307/job/20613225326
```
0.590 ERROR: unable to select packages:
61
0.590   nodejs-npm (no such package):
62
```
Missed this locally. Now `make docker` does work.
> Fix docker image after alpine version upgrade

- .coveragerc
- bouncer/_version.py
- bouncer/app.py
- bouncer/embed_detector.py
- bouncer/search.py
- bouncer/util.py
- bouncer/views.py
- tests/unit/bouncer/util_test.py
Require 100% coverage but mark existings gaps with `nocover` like we did in H. The idea is that any changes to this codebase will require the 100% coverage an ideally the existing gaps will disappear. 
Fix jinja2 issue after the upgrade.
> Fix jinja2 import after version upgrade

- requirements/requirements.in
- requirements/requirements.txt
So that Dependabot keeps it up to date.
> Make sentry-sdk a direct requirement

- bouncer/scripts/redirect.js
- bouncer/scripts/test/redirect-test.js
- bouncer/util.py
- bouncer/views.py
- tests/unit/bouncer/util_test.py
- tests/unit/bouncer/views_test.py
When following a bouncer link for an annotation, check if the annotation is a YouTube transcript annotation made using Via. If so, redirect the user to Via even if they have the extension installed.
Via's video player app does not currently record a specific marker indicating that it was used to create the annotation, but it is the only tool that will create an annotation with a `MediaTimeSelector` selector on annotations with document URLs of the form `https://www.youtube.com/watch?v={id}`.
Fixes https://github.com/hypothesis/product-backlog/issues/1604
Fixes https://github.com/hypothesis/bouncer/issues/690
> Redirect user to Via if annotation is a transcript annotation

- bouncer/app.py
I'm hoping this is going to get rid of "Discarded session update because
of missing release" error messages that `sentry_sdk` has started logging
in production every few seconds, see:
https://hypothes-is.slack.com/archives/C1MA4E9B9/p1744116427133249
The releases feature is also a useful feature in itself, so it'll be
good to make use of this. I think we may also need to do a little work
on our deployment scripts to enable the full Sentry releases feature
set, see:
https://docs.sentry.io/product/releases/setup/release-automation/github-actions/
> Enable Sentry's "releases" feature

- package-lock.json
- package.json
Our eslint shared config package has a peer dependency on `eslint-plugin-mocha` `>=5.2`, and this project also depends on `eslint` 8.
Since the most recent `eslint-plugin-mocha` version depends on eslint 9, and this project does not explicitly define a dependency on it, this causes a peer dependency conflict when installing dependencies with `npm`.
This PR adds an explicit dev dependency on `eslint-plugin-mocha@^10.5`, the latest version still supporting eslint 8, to solve this issue.
> Add explicit dependency on eslint-plugin-mocha
