hypothesis/bouncer

bouncer/scripts/redirect.js, bouncer/scripts/test/redirect-test.js, bouncer/test/views_test.py, bouncer/views.py
The Chrome extension ID that bouncer tries to talk to was hardcoded (to
my dev extension). Instead actually read the CHROME_EXTENSION_ID
environment variable, send it to the JavaScript code, and have the
JavaScript code use it.
=> Use the CHROME_EXTENSION_ID environment variable

bouncer/views.py
https://trello.com/c/scNGUMBk/330-improve-copy-to-clarify-direct-linking-functionality
=> Remove extra information for non http, https urls.

bouncer/test/views_test.py, bouncer/views.py
This is necessary for Skyliner, but frankly it's probably useful regardless, as
we can configure it to be used by the ALB ourselves if need be.
=> Add a healthcheck endpoint

Dockerfile, bin/logger, conf/supervisord.conf
~~This depends on #37 and needs to be rebased after #37 has been merged.~~
---
This will allow us to run multiple processes in the same container. One
of the next changes will be to run collectd inside the container, in
order to get system metrics on Skyliner.
=> Use supervisor to run gunicorn

Dockerfile, conf/collectd.conf
=> Ignore docker single-file mountpoints in collectd

Jenkinsfile
This updates the Jenkinsfile to match that used for h-periodic (i.e. using the pipeline library) almost exactly.
=> Use pipeline library to orchestrate build

bouncer/templates/base.html.jinja2
The common name for the organization is "Hypothesis", with no dot.
=> take the dot out of Hypothesis

.travis.yml, Makefile, bouncer/__init__.py, bouncer/views.py, tests/bouncer/util_test.py, tests/bouncer/views_test.py
Following up on https://github.com/hypothesis/bouncer/pull/154, this enables linting during the Travis build for consistency with the rest of our projects and fixes some minor code issues.
=> Fix a few lint failures and enable linting on Travis

.travis.yml, Makefile, README.rst, bouncer/__init__.py, bouncer/_version.py, bouncer/app.py, bouncer/embed_detector.py, bouncer/search.py, bouncer/sentry.py, bouncer/util.py, bouncer/views.py, tests/bouncer/search_test.py, tests/bouncer/util_test.py, tests/bouncer/views_test.py, tox.ini
And reformat all of the Python code by running `make format` once. Same as the LMS app has had for a few weeks now.
=> Add `make format` and `make checkformatting`

README.rst
Fixes https://github.com/hypothesis/product-backlog/issues/991
Add some documentation about URL syntax to Bouncer.
=> Update README with route/URL syntax information

tox.ini
Fixes an issue that is causing the tests to fail on master currently.
=> Silence a warning that Pyramid is triggering

requirements.txt
This is the result of running:
make upgrade-package name=zope.interface
=> Upgrade zope.interface to its latest version

tests/conftest.py
Just copy-pasted from LMS. Nothing in bouncer uses this yet but it will doubtless come in useful
=> Add our standard `patch` fixture

tests/bouncer/app_test.py
This doesn't test everything in app.py but it's a start.
=> Add the beginnings of app.py tests

bouncer/views.py
Also move the crash code before raising to allow it to happen in dev.
=> Add a crash end-point to allow testing of error reporting

.github/workflows/continuous-integration.yml, tox.ini
For: https://github.com/hypothesis/product-backlog/issues/1199
Discovered with: https://github.com/hypothesis/checkmate/pull/312
Also some other random small tidies
=> Tests should depend on `metadata`

README.md
https://github.com/hypothesis/playbook/issues/932
=> Post Go-Live Release workflow test

.github/workflows/codeql.yml
Added the default CodeQL GitHub Action to perform static code analysis.
https://github.com/github/codeql-action/
=> Created CodeQL Workflow

bouncer/embed_detector.py, tests/unit/bouncer/embed_detector_test.py
See https://hypothes-is.slack.com/archives/C04F8GLTT7U/p1674582774548559?thread_ts=1674129397.914749&cid=C04F8GLTT7U
=> Update Semantic Scholar URLs to support dev/staging envs

bouncer/scripts/redirect.js, bouncer/scripts/test/redirect-test.js, package-lock.json, package.json
Update formatting and linting configuration and packages to bring it in line with other projects. nb. the large diff is mostly a lockfile change from the `package-lock.json` update.
- Add Prettier configuration, copied from the client repo
- Update ESLint and eslint-config-hypothesis package
=> Update frontend formatting and linting configuration

bouncer/scripts/redirect.js, bouncer/scripts/test/redirect-test.js
**Depends on https://github.com/hypothesis/bouncer/pull/638**
If the installed Hypothesis Chrome extension supports the ["activate"](https://github.com/hypothesis/browser-extension/pull/1197) message,
use it to redirect the current tab and activate the extension.  This enables
bouncer to activate just one specific Hypothesis extension, if there are
multiple builds installed. The previous method would result in all installed
builds trying to activate.
In the process of using this API, the `redirect` function was converted
to be async, so that it can report when all of its async internal steps
are done. This makes writing the tests much easier. The tests have also
been rewritten to more clearly reflect the meaningfully different
scenarios that can occur.
Part of …
=> Use "activate" API to redirect and activate extension

.github/workflows/deploy.yml
Part of the work towards: https://github.com/hypothesis/playbook/issues/1195
=> Added new staging job to deploy.yml
